# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=25)),
                ('phoneNumber', models.IntegerField()),
                ('start_date', models.DateField()),
                ('title', models.CharField(max_length=30)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webapp_employee',
            },
        ),
    ]
