# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20160725_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(default='NA', max_length=40, verbose_name='Title'),
        ),
    ]
