# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.CharField(default='NA', max_length=60, verbose_name='Manager'),
        ),
    ]
