# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_directory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
