# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_directory', '0003_auto_20160722_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.CharField(default='NA', max_length=60, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=25, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(default='NA', max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateField(auto_now_add=True, verbose_name='Updated at'),
        ),
    ]
