# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_directory', '0005_auto_20160725_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.CharField(default='NA', max_length=60, verbose_name='Team'),
        ),
    ]
