# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_directory', '0007_auto_20160725_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
    ]
