# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_directory', '0008_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, verbose_name='Email'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee_directory_employee',
        ),
    ]
