# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_directory', '0009_auto_20160725_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='/Users/mariainesaranguren/Wizeline/mysite/media/default.jpeg', upload_to='media', verbose_name='Photo'),
        ),
    ]
