# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_directory', '0013_auto_20160726_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.CharField(default='/Users/mariainesaranguren/Wizeline/mysite/media/default.jpeg', max_length=100, verbose_name='Photo'),
        ),
    ]
