# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_directory', '0018_auto_20160802_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Start Date'),
        ),
    ]
