# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_directory', '0019_auto_20160802_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
